jobs:
  - prepare:
      filters:
        tags:
          only: /^v[0-9]+\.[0-9]+\.[0-9]+$/
        branches:
          only:
            - main
  - deploy_prod:
      requires:
        - prepare
      filters:
        tags:
          only: /^v[0-9]+\.[0-9]+\.[0-9]+$/
        branches:
          only:
            - main
