version: 2.1

setup: true

orbs:
  continuation: circleci/continuation@0.1.2
  path-filtering: circleci/path-filtering@0.0.2

commands:
  install_yarn_version:
    description: "Install specific Yarn version"
    steps:
      - run:
          name: Install specific Yarn version
          command: |
            echo 'run command1'

executors:
  default:
    docker:
      - environment:
          TZ: Asia/Tokyo
        image: circleci/node:14.15.5

jobs:
  setup:
    executor: default
    steps:
      # - checkout
      - install_yarn_version

workflows:
  generate-config:
    jobs:
      - path-filtering/filter:
          base-revision: origin/main
          config-path: .circleci/develop.yml
      # mapping: |
      #   src/.* build-code true
      #   doc/.* build-docs true
      # - continuation/continue:
      #     configuration_path: .circleci/develop.yml
      - setup
