version: 2.1

orbs:
  continuation: circleci/continuation@0.1.2
  path-filtering: circleci/path-filtering@0.0.2

install_yarn_version:
  description: "Install specific Yarn version"
  steps:
    - run:
        name: Install specific Yarn version
        command: |
          echo 'run command'

executors:
  default:
    docker:
      - environment:
          TZ: Asia/Tokyo
        image: circleci/node:14.15.5
    working_directory: ~/repo

workflows:
  use-my-orb:
    jobs:
      - continuation/continue:
          configuration_path: ./develop.yml
