version: 2.1

setup: true

orbs:
  continuation: circleci/continuation@0.1.2
  path-filtering: circleci/path-filtering@0.0.2

parameters:
  run-setup:
    description: Whether it is a setup workflow or a continuation
    type: boolean
    default: true

commands:
  install_yarn_version:
    description: "Install specific Yarn version"
    steps:
      - run:
          name: Install specific Yarn version
          command: |
            echo 'run command1'

executors:
  default:
    docker:
      - environment:
          TZ: Asia/Tokyo
        image: circleci/node:14.15.5

jobs:
  setup:
    executor: default
    steps:
      - checkout
      - install_yarn_version
      - continuation/continue:
          configuration_path: .circleci/develop.yml
          parameters: '{"run-setup":false}'
      - continuation/continue:
          configuration_path: .circleci/develop2.yml
          parameters: '{"run-setup":false}'

workflows:
  generate-config:
    when: << pipeline.parameters.run-setup >>
    jobs:
      # - path-filtering/filter:
      #     base-revision: origin/main
      #     config-path: .circleci/develop.yml
      #     filters:
      #       branches:
      #         only:
      #           - main
      # - path-filtering/filter:
      #     base-revision: origin/main
      #     config-path: .circleci/develop2.yml
      #     requires:
      #       - path-filtering/filter
      #     filters:
      #       branches:
      #         only:
      #           - main
      # mapping: |
      #   src/.* build-code true
      #   doc/.* build-docs true
      # - continuation/continue:
      #     configuration_path: .circleci/develop.yml
      - setup
