version: 2.1

setup: true

orbs:
  path-filtering: circleci/path-filtering@0.0.2

executors:
  default:
    docker:
      - environment:
          TZ: Asia/Tokyo
        image: circleci/node:14.15.5

workflows:
  generate-config:
    jobs:
      - path-filtering/filter:
          base-revision: origin/main
          config-path: .circleci/sample.yml
          mapping: |
            src/server/.* build-server true
            src/client/.* build-client true
