version: 2.1

setup: true

commands:
  install_yarn_version:
    description: "Install specific Yarn version"
    steps:
      - run:
          name: Install specific Yarn version
          command: |
            echo 'run command3'

executors:
  default:
    docker:
      - environment:
          TZ: Asia/Tokyo
        image: circleci/node:14.15.5

jobs:
  setup:
    executor: default
    steps:
      - checkout
      - install_yarn_version

workflows:
  setup:
    jobs:
      - setup
