commands:
    notify_slack_fail:
        steps:
            - slack/notify:
                custom: |
                    {
                      "text": "CircleCI job failed.",
                      "blocks": [
                        {
                          "type": "header",
                          "text": {
                            "type": "plain_text",
                            "text": "Job Failed. :red_circle:",
                            "emoji": true
                          }
                        },
                        {
                          "type": "section",
                          "fields": [
                            {
                              "type": "mrkdwn",
                              "text": "*Job*: ${CIRCLE_JOB}"
                            }
                          ]
                        },
                        {
                          "type": "section",
                          "fields": [
                            {
                              "type": "mrkdwn",
                              "text": "*Project*:\\n$CIRCLE_PROJECT_REPONAME"
                            },
                            {
                              "type": "mrkdwn",
                              "text": "*Branch*:\\n$CIRCLE_BRANCH"
                            },
                            {
                              "type": "mrkdwn",
                              "text": "*Author*:\\n$CIRCLE_USERNAME"
                            }
                          ],
                          "accessory": {
                            "type": "image",
                            "image_url": "https://assets.brandfolder.com/otz5mn-bw4j2w-6jzqo8/original/circle-logo-badge-black.png",
                            "alt_text": "CircleCI logo"
                          }
                        },
                        {
                          "type": "section",
                          "fields": [
                            {
                              "type": "mrkdwn",
                              "text": "*Mentions*:\\n$SLACK_PARAM_MENTIONS"
                            }
                          ]
                        },
                        {
                          "type": "actions",
                          "elements": [
                            {
                              "type": "button",
                              "text": {
                                "type": "plain_text",
                                "text": "View Job"
                              },
                              "url": "${CIRCLE_BUILD_URL}"
                            }
                          ]
                        }
                      ]
                    }
                event: fail
    notify_slack_pass:
        steps:
            - slack/notify:
                custom: |
                    {
                      "text": "CircleCI job succeeded!",
                      "blocks": [
                        {
                          "type": "header",
                          "text": {
                            "type": "plain_text",
                            "text": "Job Succeeded. :white_check_mark:",
                            "emoji": true
                          }
                        },
                        {
                          "type": "section",
                          "fields": [
                            {
                              "type": "mrkdwn",
                              "text": "*Job*: ${CIRCLE_JOB}"
                            }
                          ]
                        },
                        {
                          "type": "section",
                          "fields": [
                            {
                              "type": "mrkdwn",
                              "text": "*Project*:\\n$CIRCLE_PROJECT_REPONAME"
                            },
                            {
                              "type": "mrkdwn",
                              "text": "*Branch*:\\n$CIRCLE_BRANCH"
                                    },
                                    {
                              "type": "mrkdwn",
                              "text": "*Commit*:\\n$CIRCLE_SHA1"
                            },
                            {
                              "type": "mrkdwn",
                              "text": "*Author*:\\n$CIRCLE_USERNAME"
                            }
                          ],
                          "accessory": {
                            "type": "image",
                            "image_url": "https://assets.brandfolder.com/otz5mn-bw4j2w-6jzqo8/original/circle-logo-badge-black.png",
                            "alt_text": "CircleCI logo"
                          }
                        },
                        {
                          "type": "actions",
                          "elements": [
                            {
                              "type": "button",
                              "text": {
                                "type": "plain_text",
                                "text": "View Job"
                              },
                              "url": "${CIRCLE_BUILD_URL}"
                            }
                          ]
                        }
                      ]
                    }
                event: pass
executors:
    default:
        docker:
            - environment:
                TZ: Asia/Tokyo
              image: circleci/node:14.15.5
        working_directory: ~/repo
jobs:
    build-client:
        executor: default
        steps:
            - checkout
            - run:
                command: |
                    echo 'run build-client'
                name: build-client
            - notify_slack_fail
            - notify_slack_pass
    build-server:
        executor: default
        steps:
            - checkout
            - run:
                command: |
                    echo 'run build-server'
                name: build-server
            - notify_slack_fail
            - notify_slack_pass
orbs:
    slack: circleci/slack@4.3.1
parameters:
    build-client:
        default: false
        type: boolean
    build-server:
        default: false
        type: boolean
version: 2.1
workflows:
    build-client:
        jobs:
            - build-client
        when: << pipeline.parameters.build-client >>
    build-server:
        jobs:
            - build-server
        when: << pipeline.parameters.build-server >>
    version: 2

