jobs:
  - prepare:
      filters:
        branches:
          only:
            - develop
  - deploy_dev:
      requires:
        - prepare
      filters:
        branches:
          only:
            - develop
